[package]
name = "molecular_visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
glium = "0.36.0"
nalgebra = "0.33.2"
pdbtbx = "0.12.0"
anyhow = "1.0.93"
once_cell = "1.20.2"
